  version: '3.7'

  services:
    db:
      container_name: dation-db
      image: postgres
      volumes:
        - ./pgdata:/pgdata
      hostname: db
      environment:
        POSTGRES_DB: dation-db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        PGDATA: /pgdata
      ports:
        - 5432:5432
      tty: true
    app:
      container_name: dation-api
      build:
        context: .
        target: dev
        args:
          TAG: debug
      volumes:
        - ./:/go/src/app
      environment:
        DATION_DB_URL: postgres://user:password@db:5432/dation-db?sslmode=disable
        DATION_APPPORT: 8080
        ATION_APP_SECRET: example
      ports:
        - 8080:8080
      depends_on:
        - db
      links:
        - db
      tty: true