name: production deployment

on:
  push:
    branches:
    - main

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  # IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dation/dation-api
  IMAGE_NAME: us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/dation:${{ github.sha }}

jobs:
  build:
    name: production deployment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_SECRET }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
    - name: Configure docker
      run: gcloud auth configure-docker --quiet
    - name: docker build
      run: |
        docker build -t $IMAGE_NAME .
    - name: docker push
      run: |
        docker push $IMAGE_NAME
    - name: Deploy
      run: |-
        gcloud run deploy dation \
          --quiet \
          --region $GCP_REGION \
          --project $GCP_PROJECT \
          --image $IMAGE_NAME \
          --platform managed \